### ISSUE TITLE
Ajustes solapa Pending (People)

### ISSUE THREAD

**Issue by NicolasLamanuzzi** [bitex-la/compliance#346]
Según me transmite el equipo de Compliance, la solapa Pending debería ser de utilidad para poder identificar claramente las personas que están en condiciones de  ser analizadas para su posterior aprobación, rechazo o deshabilitación; así como para poder obtener un reporte que puedan compartir con Comercial y que sirva para notificar vía mailing a los clientes cuyo análisis aún está pendiente.

El primer punto mencionado es el que se abordará en este issue. La segunda cuestión, será tratada en un issue separado.

A continuación las condiciones que deben cumplirse para que una Persona aparezca en la solapa Pending:

**Personas cuyo State sea new Y que por lo menos tengan un issue en alguno de los siguientes States: new, answered u observed**

Quedo atento ante cualquier duda.

**Comment by werner** [comment]
En Compliance la solapa pending trae los issues que tengan como reason new_client, eso seguirá siendo un requerimiento o hay que quitarlo?

@NicolasLamanuzzi @EugeniaOchoa

**Comment by mdallago** [comment]
@werner escribile x mail a euge, pq no tiene acceso a ver esta issue y @NicolasLamanuzzi esta de vacaciones
