### ISSUE TITLE
How do i delete a person

### ISSUE THREAD

**Issue by abduli123** [bitex-la/compliance#350]
Hello, I have not found a button or something that allows me to delete a person

**Comment by mdallago** [comment]
Hello, you can't delete a person. but you can disable it.

**Comment by abduli123** [comment]
Ok thanks also i would like to know how i can change the language to Spanish because i have find in database info on Spanish

**Comment by abduli123** [comment]
Ok thanks also i would like to know how i can change the language to Spanish because i have find in database info on Spanish.

**Comment by mdallago** [comment]
Only English is supported

**Comment by abduli123** [comment]
Ok thank you
